### ISSUE TITLE
Consider roles of 'User Guide' and example notebooks

### ISSUE THREAD

**Issue by Guy-Sol** [Living-with-machines/MapReader#129]
There is currently quite a bit of over overlap between the 'User Guide' and example notebooks. Using them for distinct roles would help to improve the user experience.

For example, the user guide might provide further details on the specifics of each function/class, and the example notebooks then provides a working example of how these could be implement - but there are alternative ways to develop a synergy between the two.

**Comment by Guy-Sol** [comment]
Some generally good examples of supplementing documentation are `Plotly` and `OSMnx` (although they do this in very different ways):

https://plotly.com/python/
https://github.com/gboeing/osmnx-examples/tree/main/notebooks

**Comment by lakillo** [comment]
Some documentation that I helped write where we divided the information in a similar way to this suggestion: https://rvt-py.readthedocs.io/en/latest/index.html

There's an initial section called 'Getting started' which is divided up into subsections by _task_, giving a basic overview of the four main things that the package does from a user-centred pov, providing the basic chunks of code to get the tasks done.

Then there are 'Example notebooks' which are divided up by the specific _module_ used to complete tasks (each module does similar things but allowing different degrees of customisation), giving a thorough walkthough of each module from a function-centred pov.

Additionally, there is 'List of visualisations' which allows users to browse all possible outputs before using the package.

**Comment by rwood-97** [comment]
- [ ] Example notebooks to be targeted at specific user groups w/ different skill levels

**Comment by kmcdono2** [comment]
@kmcdono2 think about this

**Comment by kmcdono2** [comment]
@Guy-Sol Sorry it's taken so long to get back to you on this. And thanks @lakillo for your additional thoughts! Our thinking so far has been along these lines:

- For the moment, our core audience is people with not a lot of computational experience, so we are making the "User Guide" as easy to follow as possible, step by step, with plenty of prose to explain options and rationales for what users are doing. This might become a "Getting started", but there is probably a shorter version that would be better for that, depending on audience. 
- The User Guide is distinct from the "worked examples" where we will have different kinds of examples of uses of MapReader - these might be end to end, or they might only be for one part. They might also include examples of people using non-map data (which we don't, at the moment, have other documentation for).
- The API reference serves as the more technical documentation, with full details about every module and class.
- At the moment, you are right to point out the overlap between the notebooks in the worked examples and the User Guide: this is because the content from the worked examples used to be all we had originally. Now that we have the User Guide, we'll be revising the worked examples to have less overlap with the user guide. For ex, there will be a notebook we are using for the Launch next week that will live in worked examples and be an end-to-end example.

**Comment by kmcdono2** [comment]
I'm going to close this for now, as I think it is a more general issue that we are keeping in mind, but do have a working plan for.
