### ISSUE TITLE
write true beginners intro 

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#148]
**Is your documentation update related to a problem? Please describe.**
When working through MapReader with @jl106jml, we noted the need for a bit more of an intro to getting historians with little exp. using terminal etc.

**Describe the solution you'd like**
New page in documentation for "true beginners" who want to have a leg up in order to get started. Point to tutorials on using terminal, what is a jupyter notebook, what is a virtual env.

**Describe alternatives you've considered**
Discouraging use? But that's precisely what we don't want to do :)

**Additional context**
@kallewesterling could you share links to the tutorials you created? I'll add programming historian ones.

**Comment by kallewesterling** [comment]
A quick draft
-----

For someone who is a true beginner, it's important to first understand what a terminal is. A terminal is a command-line interface where you can type in commands and interact with your computer's operating system. It can be a powerful tool for programmers, allowing them to execute complex tasks with just a few keystrokes. However, it can also be intimidating for beginners who are not familiar with using it. Here are some resources to help you get started with using the terminal on your computer: [list tutorials]

Now that you understand what a terminal is, let's move on to understanding what a Jupyter notebook is and what a virtual environment is in Python.

A Jupyter notebook is an interactive computational environment that allows you to write and run code, visualise data, and write narrative text all in the same place. It's a popular tool among data scientists and is commonly used for data analysis, machine learning, and scientific computing. If you're new to Jupyter notebooks, here's a great place to start: [include link]. 

You will notice that many of our "worked examples" are built in Jupyter notebooks so you can test run some of this code as soon as you have understood what the notebooks are, how to set them up on your computer, and how to run code in them.

A virtual environment is a way to create an isolated environment in which you can install specific versions of packages and dependencies for your Python projects. This is useful because it allows you to avoid conflicts between different projects that may require different versions of the same package. In the installation instructions provided, there are two methods for setting up a virtual environment for MapReader: using Anaconda (also known as `conda`) or using `venv`, which is Python's native way of handling virtual environments. If you're new to virtual environments in Python, this tutorial provides a good introduction: [link]

**Comment by rwood-97** [comment]
Have added these into a ``Beginners_info.rst`` file in ``rw_docs``.

Still need to:
- [ ] Add links to tutorials etc
- [ ] Add info of what python packages are (importantly: explain that they arent the same as apps you can open from launch page/ start page)
